# Spring Boot configuration
spring:
  profiles:
    active: development
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.kaluzny: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# Configure the server to run with SSL/TLS and using HTTPS
server:
  port: 8443
  ssl:
    key-store: classpath:tomcat.keystore
    key-store-password: password
    key-password: password
  sessionTimeout: 30

#EntityManager
entityManager:
  packagesToScan: com.kaluzny.domain

# Database
database:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
  username: user
  password: user

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hbm2ddl.auto: update
  show_sql: true
  format_sql: true