# Spring Boot configuration
spring:
  profiles:
    active: production

# Logging
logging:
  file: logs/dev_app.log
  pattern:
    console: "[%-5level] %date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{15}#%line %msg\n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.kaluzny: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# Database
database:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
  username: user
  password: user

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hbm2ddl.auto: update
  show_sql: true
  format_sql: true

#EntityManager
entityManager:
  packagesToScan: com.kaluzny.domain

# Configure the server to run with SSL/TLS and using HTTPS
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: tomcatadmin
    keyStoreType: PKCS12
    keyAlias: tomcat