# Spring Boot configuration
spring:
  profiles:
    active: development
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.kaluzny: DEBUG
    org.springframework: INFO
    org.hibernate: DEBUG

# Server configuration
server:
  port: 8080
  sessionTimeout: 30

#PackagesToScan
entitymanager:
  packagesToScan: com.kaluzny.domain

# Database
dataSource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
  username: user
  password: user

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hbm2ddl.auto: update
  show_sql: true
  format_sql: true