# Spring Boot configuration
spring:
  profiles:
    active: production
# Database
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: user
    password: user
# JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
# Logging
logging:
  file: logs/dev_app.log
  pattern:
    console: "[%-5level] %date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{15}#%line %msg\n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.kaluzny: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
# Configure the server to run with SSL/TLS and using HTTPS
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: tomcatadmin
    keyStoreType: PKCS12
    keyAlias: tomcat
